export const ARTICLES_FALLBACK  = [
    {
      "type_of": "article",
      "id": 2012932,
      "title": "Enhancing Small Business Infrastructure: Practical and Cost-effective Strategies",
      "description": "In today's digital age, businesses—big and small—must constantly optimize their infrastructure to...",
      "readable_publish_date": "Sep 24 '24",
      "slug": "enhancing-small-business-infrastructure-practical-and-cost-effective-strategies-477l",
      "path": "/jecrs687/enhancing-small-business-infrastructure-practical-and-cost-effective-strategies-477l",
      "url": "https://dev.to/jecrs687/enhancing-small-business-infrastructure-practical-and-cost-effective-strategies-477l",
      "comments_count": 0,
      "public_reactions_count": 0,
      "collection_id": null,
      "published_timestamp": "2024-09-24T15:13:30Z",
      "language": "en",
      "subforem_id": null,
      "positive_reactions_count": 0,
      "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F95jsmyv4n9nrzh3trrkt.jpeg",
      "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F95jsmyv4n9nrzh3trrkt.jpeg",
      "canonical_url": "https://dev.to/jecrs687/enhancing-small-business-infrastructure-practical-and-cost-effective-strategies-477l",
      "created_at": "2024-09-24T15:13:31Z",
      "edited_at": "2025-01-02T15:00:32Z",
      "crossposted_at": null,
      "published_at": "2024-09-24T15:13:30Z",
      "last_comment_at": "2024-09-24T15:13:30Z",
      "reading_time_minutes": 5,
      "tag_list": [],
      "tags": "",
      "user": {
        "name": "Emanuel Cascone",
        "username": "jecrs687",
        "twitter_username": null,
        "github_username": "jecrs687",
        "user_id": 313863,
        "website_url": "https://github.com/jecrs687",
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F313863%2F945b0f32-91c6-43a2-83a6-ef2e6df94eb7.jpeg",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F313863%2F945b0f32-91c6-43a2-83a6-ef2e6df94eb7.jpeg"
      }
    },
    {
      "type_of": "article",
      "id": 1399605,
      "title": "Create an AMAZING readme for your github profile",
      "description": "First things first (as imagine dragons), if you want to check out my GitHub profile, visit jecrs687....",
      "readable_publish_date": "Mar 14 '23",
      "slug": "create-a-amazing-readme-for-your-github-profile-3jj0",
      "path": "/jecrs687/create-a-amazing-readme-for-your-github-profile-3jj0",
      "url": "https://dev.to/jecrs687/create-a-amazing-readme-for-your-github-profile-3jj0",
      "comments_count": 0,
      "public_reactions_count": 2,
      "collection_id": null,
      "published_timestamp": "2023-03-14T00:28:07Z",
      "language": "en",
      "subforem_id": null,
      "positive_reactions_count": 2,
      "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Flutiyuqnghlb9pg6dgb9.png",
      "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Flutiyuqnghlb9pg6dgb9.png",
      "canonical_url": "https://dev.to/jecrs687/create-a-amazing-readme-for-your-github-profile-3jj0",
      "created_at": "2023-03-13T22:09:20Z",
      "edited_at": "2023-03-26T18:12:26Z",
      "crossposted_at": null,
      "published_at": "2023-03-14T00:28:07Z",
      "last_comment_at": "2023-03-14T00:28:07Z",
      "reading_time_minutes": 3,
      "tag_list": [],
      "tags": "",
      "user": {
        "name": "Emanuel Cascone",
        "username": "jecrs687",
        "twitter_username": null,
        "github_username": "jecrs687",
        "user_id": 313863,
        "website_url": "https://github.com/jecrs687",
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F313863%2F945b0f32-91c6-43a2-83a6-ef2e6df94eb7.jpeg",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F313863%2F945b0f32-91c6-43a2-83a6-ef2e6df94eb7.jpeg"
      }
    },
    {
      "type_of": "article",
      "id": 1399560,
      "title": "Unlock Your Potential: 3 Game-Changing GitHub Repositories You Need to Explore Today!",
      "description": "GitHub is a treasure trove of learning opportunities for developers and aspiring coders. But with...",
      "readable_publish_date": "Mar 13 '23",
      "slug": "best-repositories-to-learn-something-different-487c",
      "path": "/jecrs687/best-repositories-to-learn-something-different-487c",
      "url": "https://dev.to/jecrs687/best-repositories-to-learn-something-different-487c",
      "comments_count": 0,
      "public_reactions_count": 3,
      "collection_id": null,
      "published_timestamp": "2023-03-13T20:53:10Z",
      "language": "en",
      "subforem_id": null,
      "positive_reactions_count": 3,
      "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Ftzguyoxz1f3hx9epo2ee.png",
      "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Ftzguyoxz1f3hx9epo2ee.png",
      "canonical_url": "https://dev.to/jecrs687/best-repositories-to-learn-something-different-487c",
      "created_at": "2023-03-13T20:53:10Z",
      "edited_at": "2025-01-20T10:34:42Z",
      "crossposted_at": null,
      "published_at": "2023-03-13T20:53:10Z",
      "last_comment_at": "2023-03-13T20:53:10Z",
      "reading_time_minutes": 3,
      "tag_list": [
        "programming",
        "tutorial",
        "productivity",
        "github"
      ],
      "tags": "programming, tutorial, productivity, github",
      "user": {
        "name": "Emanuel Cascone",
        "username": "jecrs687",
        "twitter_username": null,
        "github_username": "jecrs687",
        "user_id": 313863,
        "website_url": "https://github.com/jecrs687",
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F313863%2F945b0f32-91c6-43a2-83a6-ef2e6df94eb7.jpeg",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F313863%2F945b0f32-91c6-43a2-83a6-ef2e6df94eb7.jpeg"
      }
    },
    {
      "type_of": "article",
      "id": 777954,
      "title": "How to Maximize Your Profit Mining Chia: Insider Tips to Save Money and Boost Performance",
      "description": "After the initial BUUUM from the Chia cryptocurrency development—reaching over $1000 in value—the...",
      "readable_publish_date": "Aug 1 '21",
      "slug": "como-aumentar-o-lucro-com-a-chia-para-pequenos-fazendeiros-ou-iniciantes-1o2b",
      "path": "/jecrs687/como-aumentar-o-lucro-com-a-chia-para-pequenos-fazendeiros-ou-iniciantes-1o2b",
      "url": "https://dev.to/jecrs687/como-aumentar-o-lucro-com-a-chia-para-pequenos-fazendeiros-ou-iniciantes-1o2b",
      "comments_count": 0,
      "public_reactions_count": 0,
      "collection_id": null,
      "published_timestamp": "2021-08-01T00:50:48Z",
      "language": "en",
      "subforem_id": null,
      "positive_reactions_count": 0,
      "cover_image": null,
      "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Ft9f1ib85wncg1fw129xl.png",
      "canonical_url": "https://dev.to/jecrs687/como-aumentar-o-lucro-com-a-chia-para-pequenos-fazendeiros-ou-iniciantes-1o2b",
      "created_at": "2021-08-01T00:50:48Z",
      "edited_at": "2025-01-02T15:04:19Z",
      "crossposted_at": null,
      "published_at": "2021-08-01T00:50:48Z",
      "last_comment_at": "2021-08-01T00:50:48Z",
      "reading_time_minutes": 1,
      "tag_list": [
        "chia",
        "plots",
        "minerar",
        "lucro"
      ],
      "tags": "chia, plots, minerar, lucro",
      "user": {
        "name": "Emanuel Cascone",
        "username": "jecrs687",
        "twitter_username": null,
        "github_username": "jecrs687",
        "user_id": 313863,
        "website_url": "https://github.com/jecrs687",
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F313863%2F945b0f32-91c6-43a2-83a6-ef2e6df94eb7.jpeg",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F313863%2F945b0f32-91c6-43a2-83a6-ef2e6df94eb7.jpeg"
      }
    },
    {
      "type_of": "article",
      "id": 777953,
      "title": "Unlock the Full Potential of Your Storage: Boost Performance with MergerFS and RAID 0!",
      "description": "To address this issue, I recommend leveraging two powerful technologies: MergerFS and RAID...",
      "readable_publish_date": "Aug 1 '21",
      "slug": "criar-plots-em-ssds-com-menos-de-249g-livres-linux-2o0e",
      "path": "/jecrs687/criar-plots-em-ssds-com-menos-de-249g-livres-linux-2o0e",
      "url": "https://dev.to/jecrs687/criar-plots-em-ssds-com-menos-de-249g-livres-linux-2o0e",
      "comments_count": 0,
      "public_reactions_count": 0,
      "collection_id": null,
      "published_timestamp": "2021-08-01T00:49:33Z",
      "language": "en",
      "subforem_id": null,
      "positive_reactions_count": 0,
      "cover_image": null,
      "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2F79abu0i6pp26ksb98tdo.png",
      "canonical_url": "https://dev.to/jecrs687/criar-plots-em-ssds-com-menos-de-249g-livres-linux-2o0e",
      "created_at": "2021-08-01T00:49:33Z",
      "edited_at": "2025-01-20T10:32:14Z",
      "crossposted_at": null,
      "published_at": "2021-08-01T00:49:33Z",
      "last_comment_at": "2021-08-01T00:49:33Z",
      "reading_time_minutes": 1,
      "tag_list": [
        "chia",
        "ssds",
        "mergerfs",
        "linux"
      ],
      "tags": "chia, ssds, mergerfs, linux",
      "user": {
        "name": "Emanuel Cascone",
        "username": "jecrs687",
        "twitter_username": null,
        "github_username": "jecrs687",
        "user_id": 313863,
        "website_url": "https://github.com/jecrs687",
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F313863%2F945b0f32-91c6-43a2-83a6-ef2e6df94eb7.jpeg",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F313863%2F945b0f32-91c6-43a2-83a6-ef2e6df94eb7.jpeg"
      }
    },
    {
      "type_of": "article",
      "id": 777942,
      "title": "Turn Your Hard Drives Into Super SSDs: The Ultimate Guide to RAID 0 and LVM Mastery",
      "description": "Some cryptocurrencies use hard drives (HDDs) for mining — yes, it’s strange, but it happens! And they...",
      "readable_publish_date": "Aug 1 '21",
      "slug": "criando-plots-chias-em-hds-usando-o-maximo-de-desempenho-no-linux-4ecf",
      "path": "/jecrs687/criando-plots-chias-em-hds-usando-o-maximo-de-desempenho-no-linux-4ecf",
      "url": "https://dev.to/jecrs687/criando-plots-chias-em-hds-usando-o-maximo-de-desempenho-no-linux-4ecf",
      "comments_count": 0,
      "public_reactions_count": 0,
      "collection_id": null,
      "published_timestamp": "2021-08-01T00:14:56Z",
      "language": "en",
      "subforem_id": null,
      "positive_reactions_count": 0,
      "cover_image": null,
      "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Farticles%2Flp8ww6ovm1mr25qy7xvc.png",
      "canonical_url": "https://dev.to/jecrs687/criando-plots-chias-em-hds-usando-o-maximo-de-desempenho-no-linux-4ecf",
      "created_at": "2021-08-01T00:14:56Z",
      "edited_at": "2025-01-20T10:30:24Z",
      "crossposted_at": null,
      "published_at": "2021-08-01T00:14:56Z",
      "last_comment_at": "2021-08-01T00:14:56Z",
      "reading_time_minutes": 3,
      "tag_list": [
        "hds",
        "desempenho",
        "ssd",
        "hardware"
      ],
      "tags": "hds, desempenho, ssd, hardware",
      "user": {
        "name": "Emanuel Cascone",
        "username": "jecrs687",
        "twitter_username": null,
        "github_username": "jecrs687",
        "user_id": 313863,
        "website_url": "https://github.com/jecrs687",
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F313863%2F945b0f32-91c6-43a2-83a6-ef2e6df94eb7.jpeg",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F313863%2F945b0f32-91c6-43a2-83a6-ef2e6df94eb7.jpeg"
      }
    },
    {
      "type_of": "article",
      "id": 263786,
      "title": "Consumindo a Api do dev.to",
      "description": "O Dev.to fornece uma API simples e fácil de consumir com operações básicas, como:     Obter...",
      "readable_publish_date": "Feb 18 '20",
      "slug": "consumindo-a-api-do-dev-to-4n5e",
      "path": "/jecrs687/consumindo-a-api-do-dev-to-4n5e",
      "url": "https://dev.to/jecrs687/consumindo-a-api-do-dev-to-4n5e",
      "comments_count": 1,
      "public_reactions_count": 6,
      "collection_id": null,
      "published_timestamp": "2020-02-18T13:39:00Z",
      "language": "pt",
      "subforem_id": null,
      "positive_reactions_count": 6,
      "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fi%2F3bo4t9vnulazpzuf4aam.png",
      "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fi%2F3bo4t9vnulazpzuf4aam.png",
      "canonical_url": "https://dev.to/jecrs687/consumindo-a-api-do-dev-to-4n5e",
      "created_at": "2020-02-18T13:39:00Z",
      "edited_at": "2024-02-23T03:59:17Z",
      "crossposted_at": null,
      "published_at": "2020-02-18T13:39:00Z",
      "last_comment_at": "2021-07-03T05:44:43Z",
      "reading_time_minutes": 1,
      "tag_list": [
        "javascript",
        "axios",
        "react"
      ],
      "tags": "javascript, axios, react",
      "user": {
        "name": "Emanuel Cascone",
        "username": "jecrs687",
        "twitter_username": null,
        "github_username": "jecrs687",
        "user_id": 313863,
        "website_url": "https://github.com/jecrs687",
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F313863%2F945b0f32-91c6-43a2-83a6-ef2e6df94eb7.jpeg",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F313863%2F945b0f32-91c6-43a2-83a6-ef2e6df94eb7.jpeg"
      }
    },
    {
      "type_of": "article",
      "id": 263363,
      "title": "Unlock the Secret to Easily Host Your React Resume on GitHub Pages (No More Hassles!)",
      "description": "After facing numerous challenges with GitHub Pages' system, I must admit that finding an effortless...",
      "readable_publish_date": "Feb 17 '20",
      "slug": "como-criar-um-web-curriculum-no-github-pages-com-reactjs-5a0",
      "path": "/jecrs687/como-criar-um-web-curriculum-no-github-pages-com-reactjs-5a0",
      "url": "https://dev.to/jecrs687/como-criar-um-web-curriculum-no-github-pages-com-reactjs-5a0",
      "comments_count": 0,
      "public_reactions_count": 4,
      "collection_id": null,
      "published_timestamp": "2020-02-17T20:12:47Z",
      "language": "en",
      "subforem_id": null,
      "positive_reactions_count": 4,
      "cover_image": "https://media2.dev.to/dynamic/image/width=1000,height=420,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fi%2F1f1y9ulroe7kgl9t16kj.jpg",
      "social_image": "https://media2.dev.to/dynamic/image/width=1000,height=500,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fi%2F1f1y9ulroe7kgl9t16kj.jpg",
      "canonical_url": "https://dev.to/jecrs687/como-criar-um-web-curriculum-no-github-pages-com-reactjs-5a0",
      "created_at": "2020-02-17T20:12:47Z",
      "edited_at": "2025-01-20T10:33:35Z",
      "crossposted_at": null,
      "published_at": "2020-02-17T20:12:47Z",
      "last_comment_at": "2020-02-17T20:12:47Z",
      "reading_time_minutes": 1,
      "tag_list": [],
      "tags": "",
      "user": {
        "name": "Emanuel Cascone",
        "username": "jecrs687",
        "twitter_username": null,
        "github_username": "jecrs687",
        "user_id": 313863,
        "website_url": "https://github.com/jecrs687",
        "profile_image": "https://media2.dev.to/dynamic/image/width=640,height=640,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F313863%2F945b0f32-91c6-43a2-83a6-ef2e6df94eb7.jpeg",
        "profile_image_90": "https://media2.dev.to/dynamic/image/width=90,height=90,fit=cover,gravity=auto,format=auto/https%3A%2F%2Fdev-to-uploads.s3.amazonaws.com%2Fuploads%2Fuser%2Fprofile_image%2F313863%2F945b0f32-91c6-43a2-83a6-ef2e6df94eb7.jpeg"
      }
    }
  ] 