export const GITHUB_FALLBACK = {
    "login": "jecrs687",
    "id": 45917859,
    "node_id": "MDQ6VXNlcjQ1OTE3ODU5",
    "avatar_url": "https://avatars.githubusercontent.com/u/45917859?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/jecrs687",
    "html_url": "https://github.com/jecrs687",
    "followers_url": "https://api.github.com/users/jecrs687/followers",
    "following_url": "https://api.github.com/users/jecrs687/following{/other_user}",
    "gists_url": "https://api.github.com/users/jecrs687/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/jecrs687/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/jecrs687/subscriptions",
    "organizations_url": "https://api.github.com/users/jecrs687/orgs",
    "repos_url": "https://api.github.com/users/jecrs687/repos",
    "events_url": "https://api.github.com/users/jecrs687/events{/privacy}",
    "received_events_url": "https://api.github.com/users/jecrs687/received_events",
    "type": "User",
    "user_view_type": "public",
    "site_admin": false,
    "name": "Emanuel Cascone",
    "company": "Zumbat hub",
    "blog": "jecrs687.github.io",
    "location": "Italy",
    "email": null,
    "hireable": true,
    "bio": "🌍 Brazilian-Italian developer passionate about technology. Skilled in backend, front-end, and mobile apps. Always learning and striving for growth.",
    "twitter_username": null,
    "public_repos": 37,
    "public_gists": 1,
    "followers": 48,
    "following": 33,
    "created_at": "2018-12-16T14:31:36Z",
    "updated_at": "2025-03-28T10:47:35Z"
}